CREATE VIEW NLALRegularSeasonStats_byPlayer AS
    SELECT _yearID,
           TEAM,
           Player,
           _playerID,
           _teamID,
           _stint,
           sum(F_Game) AS F_Game,
           sum(F_GameStarted) AS F_GameStarted,
           sum(F_OutPlayed) AS F_OutPlayed,
           sum(F_Putout) AS F_Putout,
           sum(F_Assist) AS F_Assist,
           sum(F_Error) AS F_Error,
           sum(F_DoublePlay) AS F_DoublePlay,
           sum(F_CatcherPassedBall) AS F_CatcherPassedBall,
           sum(F_CatcherWildPitch) AS F_CatcherWildPitch,
           sum(F_CatcherOppStolenBase) AS F_CatcherOppStolenBase,
           sum(F_CatcherOppCaughtStealing) AS F_CatcherOppCaughtStealing,
           sum(F_ZoneRating) AS F_ZoneRating,
           B_Game,
           B_AtBats,
           B_Run,
           B_Hit,
           B_Double,
           B_Triple,
           B_Homer,
           B_RBI,
           B_StolenBase,
           B_CaughtStealing,
           B_Walk,
           B_StrikeOuts,
           B_IntentWalk,
           B_HitbyPitch,
           B_SacrificeHit,
           B_SacrificeFly,
           B_GroundDoublePlay,
           P_Win,
           P_Loss,
           P_Game,
           P_GameStarted,
           P_CompleteGame,
           P_Shutout,
           P_Save,
           P_OutsPitched,
           P_Hits,
           P_EarnedRun,
           P_HomeRun,
           P_Walk,
           P_StrikeOut,
           P_OppBattAvg,
           P_EarnedRunAvg,
           P_IntentWalk,
           P_WildPitch,
           P_HitBatter,
           P_Balk,
           P_BatterFaced,
           P_GameFinished,
           P_RunAllowed,
           P_OppSacrificeHit,
           P_OppSacrificeFly
      FROM NLALRegularSeasonStats_byPosition
     GROUP BY _yearID,
              TEAM,
              Player,
              _playerID,
              _teamID,
              _stint,
              B_Game,
              B_AtBats,
              B_Run,
              B_Hit,
              B_Double,
              B_Triple,
              B_Homer,
              B_RBI,
              B_StolenBase,
              B_CaughtStealing,
              B_Walk,
              B_StrikeOuts,
              B_IntentWalk,
              B_HitbyPitch,
              B_SacrificeHit,
              B_SacrificeFly,
              B_GroundDoublePlay,
              P_Win,
              P_Loss,
              P_Game,
              P_GameStarted,
              P_CompleteGame,
              P_Shutout,
              P_Save,
              P_OutsPitched,
              P_Hits,
              P_EarnedRun,
              P_HomeRun,
              P_Walk,
              P_StrikeOut,
              P_OppBattAvg,
              P_EarnedRunAvg,
              P_IntentWalk,
              P_WildPitch,
              P_HitBatter,
              P_Balk,
              P_BatterFaced,
              P_GameFinished,
              P_RunAllowed,
              P_OppSacrificeHit,
              P_OppSacrificeFly;